# Generated by Django 5.0.1 on 2024-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uz_ticket_checker', '0002_ticketsearchparameter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketsearchparameter',
            name='seat_type',
            field=models.ManyToManyField(related_name='seat_types', to='uz_ticket_checker.seattype'),
        ),
        migrations.AlterField(
            model_name='ticketsearchparameter',
            name='train_number',
            field=models.ManyToManyField(related_name='train_numbers', to='uz_ticket_checker.trainnumber'),
        ),
        migrations.AlterField(
            model_name='ticketsearchparameter',
            name='wagon_type',
            field=models.ManyToManyField(related_name='wagon_types', to='uz_ticket_checker.wagontype'),
        ),
    ]
