# Generated by Django 5.0.1 on 2024-03-30 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uz_ticket_checker', '0003_alter_ticketsearchparameter_seat_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seattype',
            name='seat_type_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='seat type name'),
            preserve_default=False,
        ),
    ]
