# Generated by Django 5.0.1 on 2024-03-05 14:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letter', models.CharField(max_length=3, verbose_name='letter')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('places', models.IntegerField(default=0, verbose_name='free places')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('value', models.IntegerField(unique=True, verbose_name='value')),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=20, verbose_name='number')),
                ('category', models.IntegerField(blank=True, verbose_name='category')),
                ('date_at', models.DateField(default=django.utils.timezone.now, verbose_name='at date')),
                ('time_at', models.TimeField(default=django.utils.timezone.now, verbose_name='at time')),
                ('places', models.ManyToManyField(related_name='trains', to='booking_uz_gov_ua.place')),
            ],
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('date_at', models.DateField(default=django.utils.timezone.now, verbose_name='at date')),
                ('time_at', models.TimeField(default=django.utils.timezone.now, verbose_name='at time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station_checkers', to='booking_uz_gov_ua.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station_checkers', to='booking_uz_gov_ua.station')),
                ('trains', models.ManyToManyField(blank=True, related_name='checkers', to='booking_uz_gov_ua.train')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
