# Generated by Django 5.0.1 on 2024-03-28 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalsetting',
            name='type_name',
        ),
        migrations.AddField(
            model_name='personalsetting',
            name='is_vip',
            field=models.BooleanField(default=False, verbose_name='vip'),
        ),
        migrations.AlterField(
            model_name='personalsetting',
            name='max_query_number',
            field=models.IntegerField(default=10, verbose_name='max query number'),
        ),
    ]
