# Generated by Django 5.0.1 on 2024-03-23 22:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_useraccounttype_user_telegram_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ParameterCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('param_category_name', models.CharField(max_length=150, verbose_name='parameter category name')),
            ],
        ),
        migrations.CreateModel(
            name='CheckerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('update_period', models.IntegerField(verbose_name='update period (minutes)')),
                ('last_run_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last run date')),
                ('task_params', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='accounts.baseparameter', verbose_name='parameters')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='baseparameter',
            name='param_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameter_category', to='accounts.parametercategory', verbose_name='Parameter category'),
        ),
    ]
