version: '3.8'

volumes:
  redis:
    driver: local

x-base: &base-backend
  build: .
  volumes:
    - .:/code:delegated
  depends_on:
    - redis

services:

  redis:
    image: "redis:6.0"
    volumes:
      - redis:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  celery_worker:
    <<: *base-backend
    env_file:
      - .env
    command: celery -A apps worker -l INFO -P solo


  celery_beat:
    <<: *base-backend
    env_file:
      - .env
    command: celery -A apps beat -l info


  web_app:
    <<: *base-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000