# Generated by Django 5.0.1 on 2024-03-18 11:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, verbose_name='code')),
                ('name', models.CharField(max_length=100, verbose_name='title')),
                ('bus_name', models.CharField(blank=True, default='', max_length=100, verbose_name='bus name')),
            ],
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_available', models.BooleanField(default=False, verbose_name='available')),
                ('date_at', models.DateField(default=django.utils.timezone.now, verbose_name='at date')),
                ('time_at', models.TimeField(default=django.utils.timezone.now, verbose_name='at time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_ua_checkers', to=settings.AUTH_USER_MODEL)),
                ('from_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_station_checkers', to='tickets_ua.station')),
                ('to_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_station_checkers', to='tickets_ua.station')),
            ],
            options={
                'verbose_name': 'checker',
                'verbose_name_plural': 'checkers',
            },
        ),
    ]
