# Generated by Django 5.0.1 on 2024-03-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets_ua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name='available'),
        ),
    ]
