# Generated by Django 5.0.1 on 2024-03-14 07:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('code', models.IntegerField(unique=True, verbose_name='code')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('url', models.CharField(max_length=255, verbose_name='url')),
                ('path', models.CharField(blank=True, max_length=100, null=True, verbose_name='token')),
                ('is_link', models.BooleanField(default=False, verbose_name='link')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='hotline_ua.category')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('type_name', models.CharField(choices=[('default', 'default')], max_length=20, verbose_name='type')),
                ('code', models.IntegerField(verbose_name='code')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='hotline_ua.category')),
            ],
            options={
                'unique_together': {('code', 'category')},
            },
        ),
        migrations.CreateModel(
            name='Checker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='created date')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='updated date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_available', models.BooleanField(default=False, verbose_name='available')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkers', to='hotline_ua.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkers', to=settings.AUTH_USER_MODEL)),
                ('filters', models.ManyToManyField(blank=True, related_name='checkers', to='hotline_ua.filter')),
            ],
            options={
                'verbose_name': 'checker',
                'verbose_name_plural': 'checkers',
            },
        ),
    ]
