# Generated by Django 5.0.1 on 2024-03-15 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotline_ua', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checker',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkers', to='hotline_ua.category'),
        ),
        migrations.AlterField(
            model_name='checker',
            name='filters',
            field=models.ManyToManyField(related_name='checkers', to='hotline_ua.filter'),
        ),
        migrations.AlterField(
            model_name='filter',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='hotline_ua.category'),
        ),
    ]
