# Generated by Django 5.0.1 on 2024-03-17 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotline_ua', '0002_alter_checker_category_alter_checker_filters_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='filter',
            options={'verbose_name': 'filter', 'verbose_name_plural': 'filters'},
        ),
        migrations.AlterUniqueTogether(
            name='filter',
            unique_together=set(),
        ),
    ]
