# Generated by Django 5.0.1 on 2024-03-29 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkertask',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='delete'),
        ),
    ]
