USER_UPDATE_PERIOD_DEFAULT = 0
TASK_UPDATE_PERIOD_DEFAULT = 5
MAX_QUERY_NUMBER_DEFAULT = 10

DATA_FORMAT_DEFAULT = "%Y-%m-%d"
TIME_FORMAT_DEFAULT = "%H:%M"

ACTIVE_TITLE_CATEGORIES_DEFAULT = ["Побутова техніка", "Комп'ютери", "Смартфони"]
TITLE_REGEX_DEFAULT = r"^[a-zA-Zа-яА-ЯєіїЄІЇ0-9\-'. ]{2,100}$"


RUN_CHECKER_INTERVAL_DEFAULT = 5
EXPIRES_RUN_CHECKER_INTERVAL_DEFAULT = 4
